name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: Analyze only Projekt4 on SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: Projekt4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
